package controller;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

import controller.events.LocalEvents;
import javafx.animation.AnimationTimer;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.Button;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.control.Tooltip;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.scene.text.Font;
import main.Main;
import model.Game;
import model.Location;
import model.Map;
import model.OverWorld;
import model.Profile;
import model.entity.Entity;
import model.entity.Sprite;
import model.texture.Texture;
import model.tile.Tile;
import model.tile.Tiles;
import model.tile.npb.classrooms.NPBFloor1Rooms;

/**
 * 
 * @author Tyler Clarkson
 * 
 *         The LocalViewController class initializes the local view and handles
 *         events generated within the local view
 *
 */
@SuppressWarnings("unused")
public class LocalViewController implements EventHandler<ActionEvent> {

	@FXML
	public Label displayName; // label that displays user's name
	@FXML
	private Canvas mapCanvas; // canvas for map
	@FXML
	public Label infoLabel; // label that displays information to the user
	@FXML
	private Button zoom; // button used for zooming in or out
	@FXML
	private Button walkOrRun; // button used to toggle walk/run
	@FXML
	public HBox labelBox; // container for infoLabel
	/**
	 * TextField the user will enter the room number they are searching for
	 * PromptText will be current room
	 */
	@FXML
	private TextField rNumberTextField;
	
	@FXML
	private Button search;
	
	/**
	 * Initializes the Local View
	 */
	@FXML
	private void initialize() {
		Game game = new Game(mapCanvas, infoLabel);
		displayName.setText("Welcome, " + StartViewController.currentUser.getFirstName());	
		labelBox.setOnMousePressed(Game.mc);
		Game.animator.start(); // start the game loop
		labelBox.setOnMouseEntered(new ToolTipController());
		}		
	

	/**
	 * Handles Events generated by the LocalView
	 * 
	 * @param event
	 *            ActionEvent to be handled
	 */
	@Override
	public void handle(ActionEvent event) {
		String eventSource = event.getSource().toString();
		
		if(eventSource.contains("Save")) {
			LocalEvents.Save(event, Game.sprite.getX(), Game.sprite.getY());
		} else if(eventSource.contains("Map")) {
			LocalEvents.Map(event);
		} else if(eventSource.contains("zoom")) {
			LocalEvents.Zoom(event, zoom);
		} else if(walkOrRun.getText().equals("Walk") || walkOrRun.getText().equals("Run")) {
			LocalEvents.WalkOrRun(event, walkOrRun);
		}
	}
	public void handleSearch(ActionEvent event) {
		 if(search.getText().equals("Search") || search.getText().equals("Back")){
				LocalEvents.Search(event, rNumberTextField, search);
			}
	}
	
}
